config/routes.rb
Rails.application.routes.draw do
  root to: 'dishes#index'
  
  resources :dishes
  
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  
  get 'signup', to: 'users#new'
  resources :users, only: [:create]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/dish.rb
class Dish < ApplicationRecord
  belongs_to :user
  
  validates :content, presence: true, length: { maximum: 255 }
end

app/models/user.rb
class User < ApplicationRecord
  has_many :dishes
  
  before_save { self.email.downcase! }
  validates :name,  presence: true, length: { maximum: 20 }
  validates :email, presence: true, length: { maximum: 300 }, format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i }, uniqueness: { case_sensitive: false }
  has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include SessionsHelper
  include Pagy::Backend
  
  private
  
  def require_user_logged_in
    unless logged_in?
      redirect_to login_url
    end
  end
end

app/controllers/dishes_controller.rb
class DishesController < ApplicationController
  before_action :require_user_logged_in 
  before_action :correct_dish, only: [:show, :edit, :update, :destroy]
  
  def index
    @dish = current_user.dishes.build
    @pagy, @dishes = pagy(current_user.dishes.order(id: :desc))
    
    @sum = 0
    current_user.dishes.each do |d|
      @sum += d.vegetables.to_i
    
    end
    @count = current_user.dishes.count
    
    if @count == 0
      @ave = 0
    else
    @ave = @sum/@count
    end
  end

  def show
  end

  def new
    @dish = Dish.new
  end

  def create
    @dish = current_user.dishes.build(dish_params)
    if @dish.save
      flash[:success] = '食事の記録に成功しました'
      redirect_to @dish
    else
      flash.now[:danger] = '食事の記録に失敗しました'
      render :new
    end
  end

  def edit
  end

  def update
    if @dish.update(dish_params)
      flash[:success] = '更新に成功しました'
      redirect_to @dish
    else
      flash.now[:danger] = '更新に失敗しました'
      render :edit
    end
  end

  def destroy
    @dish.destroy
    
    flash[:success] = '記録が正常に削除されました'
    redirect_to dishes_url
  end
  
  private
  def correct_dish
    @dish = current_user.dishes.find_by(id: params[:id])
    redirect_to root_url unless @dish
  end
  def dish_params
    params.require(:dish).permit(:content, :vegetables)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    email = params[:session][:email].downcase
    password = params[:session][:password]
    if login(email, password)
      flash[:success] = 'ログインに成功しました。'
      redirect_to root_url
    else
      flash.now[:danger] = 'ログインに失敗しました。'
      render :new
    end
  end

  def destroy
    session[:user_id] = nil
    flash[:success] = 'ログアウトしました。'
    redirect_to root_url
  end
  
    private

  def login(email, password)
    @user = User.find_by(email: email)
    if @user && @user.authenticate(password)
      # ログイン成功
      session[:user_id] = @user.id
      return true
    else
      # ログイン失敗
      return false
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)

    if @user.save
      flash[:success] = 'ユーザを登録しました。'
      redirect_to root_url
    else
      flash.now[:danger] = 'ユーザの登録に失敗しました。'
      render :new
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  include Pagy::Frontend
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end

  def logged_in?
    !!current_user
  end
end

app/views/dishes/_form.html.erb
<%= form_with(model: dish) do |f| %>

  <%= render 'layouts/error_messages', model: f.object %>
  
  <div class="mb3">
  <%= f.label :content, '料理名' %>
  <%= f.text_field :content, class: 'form-control' %>
  </div>
  <div class="mb3">
  <%= f.label :vegetables, '野菜の種数' %>
  <%= f.text_field :vegetables, class: 'form-control' %>
  </div>
  <%= f.submit '記録', class: 'btn btn-primary' %>
<% end %>

app/views/dishes/edit.html.erb
<h1>id: <%= @dish.id %> の編集ページ</h1>
<%= render 'form', dish: @dish %>

<%= link_to '一覧に戻る', dishes_path %>

app/views/dishes/index.html.erb
<h1>食事記録</h1>

  <h3>ランク</h3>
  <% if @ave < 3 %>
  <p>biginner</p>
  <% elsif @ave < 5  %>
  <p>middle</p>
  <% elsif %>
  <p>expert</p>
  <% end %>
  
  <table class="table table-striped">
    <thead>
      <tr>
        <th>id</th>
        <th>料理名</th>
        <th>野菜</th>
      </tr>
    </thead>
    <tbody>
      <% @dishes.each do |dish| %>
        <tr>
          <td><%= link_to dish.id, dish %></td>
          <td><%= dish.content %></td>
          <td><%= dish.vegetables %>種類</td>
        </tr>
      <% end %>
    </tbody>
  </table>
<%== pagy_nav(@pagy) %>

<%= link_to '記録する', new_dish_path, class: "btn btn-primary" %>

app/views/dishes/new.html.erb
<h1>記入ページ</h1>

<%= render 'form', dish: @dish %>

<%= link_to '一覧に戻る', dishes_path %>

app/views/dishes/show.html.erb
<h1>id:<%= @dish.id %> の詳細ページ</h1>
<table class="table table-bordered">
  <tr>
    <th>id</th>
    <td><%= @dish.id %></td>
  </tr>
  <tr>
    <th>料理名</th>
    <td><%= @dish.content %></td>
  </tr>
  <tr>
    <th>野菜</th>
    <td><%= @dish.vegetables %>種類</td>
  </tr>
</table>
<%= link_to 'この記録を編集する', edit_dish_path(@dish), class: "btn btn-secondary" %>
<%= link_to 'この記録を削除する', @dish, method: :delete, data: { confirm: '本当に削除してよろしいですか?' }, class: "btn btn-danger" %>

app/views/layouts/_error_messages.html.erb
<% if model.errors.any? %>
  <div id="error_explanation" class="alert alert-warning">
    <ul class="mb-0">
      <% model.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/layouts/_flash_messages.html.erb
<% flash.each do |message_type, message| %>
  <div class="alert alert-<%= message_type %>"><%= message %></div>
<% end %>

app/views/layouts/_navbar.html.erb
<header class="mb-4">
  <nav class="navbar navbar-expand-sm navbar-dark bg-dark">
    <div class="container-fluid ps-5 pe-5">
      <a class="navbar-brand" href="/">GreenDish</a>

      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent">
        <span class="navbar-toggler-icon"></span>
      </button>


      <div class="collapse navbar-collapse justify-content-end" id="navbarSupportedContent">
        <ul class="navbar-nav">
          <% if logged_in? %>
            <li class="nav-item"><%= link_to  '新規タスクの追加', new_dish_path, class: 'nav-link' %></li>
            <li class="nav-item"><%= link_to 'Logout', logout_path, method: :delete, class: 'nav-link' %></li>
          <% else %>
            <li class="nav-item"><%= link_to  'Login', login_path, class: 'nav-link' %></li>
          <% end %>
        </ul>
      </div>
    </div>
  </nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Greendish</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css">

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/js/bootstrap.bundle.min.js"></script>
  </head>

  <body>
    <%= render 'layouts/navbar' %>
    
    <div class="container">
    <%= render 'layouts/flash_messages' %> 
    
    <%= yield %>
    </div>
  </body>
</html>

app/views/users/new.html.erb
<div class="text-center">
  <h1>Sign up</h1>
</div>

<div class="row">
  <div class="col-sm-6 offset-sm-3">

    <%= form_with(model: @user) do |f| %>
      <%= render 'layouts/error_messages', model: f.object %>

      <div class="mb-3">
        <%= f.label :name, 'Name' %>
        <%= f.text_field :name, class: 'form-control' %>
      </div>

      <div class="mb-3">
        <%= f.label :email, 'Email' %>
        <%= f.email_field :email, class: 'form-control' %>
      </div>

      <div class="mb-3">
        <%= f.label :password, 'Password' %>
        <%= f.password_field :password, class: 'form-control' %>
      </div>

      <div class="mb-3">
        <%= f.label :password_confirmation, 'Confirmation' %>
        <%= f.password_field :password_confirmation, class: 'form-control' %>
      </div>

      <%= f.submit 'Sign up', class: 'btn btn-primary w-100' %>
    <% end %>
  </div>
</div>